---
# Web frontend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'server:3001'
    spec:
      containers:
        - name: client
          image: tallengft/fake-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: 'UPSTREAM_URIS'
              value: 'http://localhost:3001'

---
# Service to expose web frontend

apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000