# This is a basic workflow to help you get started with Actions

name: CI-Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Builds Docker Image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/tallengft/server:latest
        working-directory: ./server
     
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          working-directory: ./server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: tallengft/server
